"""Constants for the MUD game model components."""

# Stat names
STR = "str"
CONSTITUTION = "constitution"
DEX = "dex"
INT = "int"
WIS = "wis"
LUCK = "luck"
PHYSICAL_ENDURANCE = "physical_endurance"
MENTAL_ENDURANCE = "mental_endurance"
CHARISMA = "charisma"
EYESIGHT = "eyesight"
NIGHT_VISION = "night_vision"
STEALTH = "stealth"

# Core stats list
CORE_STATS = [STR, CONSTITUTION, DEX, INT, WIS, LUCK]

# Auxiliary stats list
AUXILIARY_STATS = [
    PHYSICAL_ENDURANCE,
    MENTAL_ENDURANCE,
    CHARISMA,
    EYESIGHT,
    NIGHT_VISION,
    STEALTH,
]

# Item types
ITEM_TYPE_WEAPON = "weapon"
ITEM_TYPE_WEARABLE = "wearable"
ITEM_TYPE_CONSUMABLE = "consumable"
ITEM_TYPES = [ITEM_TYPE_WEAPON, ITEM_TYPE_WEARABLE, ITEM_TYPE_CONSUMABLE]

# Weapon types
WEAPON_TYPE_MELEE = "melee"
WEAPON_TYPE_RANGED = "ranged"
WEAPON_TYPES = [WEAPON_TYPE_MELEE, WEAPON_TYPE_RANGED]

# Melee weapon subtypes
MELEE_BLADED = "bladed"
MELEE_BLUNT = "blunt"
MELEE_FLAILED = "flailed"
MELEE_SUBTYPES = [MELEE_BLADED, MELEE_BLUNT, MELEE_FLAILED]

# Ranged weapon subtypes
RANGED_BOW = "bow"
RANGED_THROWABLE = "throwable"
RANGED_SUBTYPES = [RANGED_BOW, RANGED_THROWABLE]

# Skill types
SKILL_TYPE_ATTACK = "attack"
SKILL_TYPE_BUFF = "buff"
SKILL_TYPE_DEBUFF = "debuff"
SKILL_TYPE_REGENERATIVE = "regenerative"
SKILL_TYPE_PROCESS = "process"
SKILL_TYPES = [
    SKILL_TYPE_ATTACK,
    SKILL_TYPE_BUFF,
    SKILL_TYPE_DEBUFF,
    SKILL_TYPE_REGENERATIVE,
    SKILL_TYPE_PROCESS,
]

# Attack skill subtypes
ATTACK_PHYSICAL = "physical"
ATTACK_ELEMENTAL = "elemental"
ATTACK_SUBTYPES = [ATTACK_PHYSICAL, ATTACK_ELEMENTAL]

# Elemental types
ELEMENT_EARTH = "earth"
ELEMENT_WATER = "water"
ELEMENT_AIR = "air"
ELEMENT_FIRE = "fire"
ELEMENTS = [ELEMENT_EARTH, ELEMENT_WATER, ELEMENT_AIR, ELEMENT_FIRE]

# Default elemental affinity (base value for all elements)
DEFAULT_ELEMENTAL_AFFINITY = 1.0

# Effector types (replaces functional node types)
EFFECTOR_TYPE_DAMAGE = "damage"
EFFECTOR_TYPE_REGENERATIVE = "regenerative"
EFFECTOR_TYPE_BUFF = "buff"
EFFECTOR_TYPE_DEBUFF = "debuff"
EFFECTOR_TYPE_PROCESS = "process"
EFFECTOR_TYPES = [
    EFFECTOR_TYPE_DAMAGE,
    EFFECTOR_TYPE_REGENERATIVE,
    EFFECTOR_TYPE_BUFF,
    EFFECTOR_TYPE_DEBUFF,
    EFFECTOR_TYPE_PROCESS,
]

# Functional node types (deprecated - use EFFECTOR_TYPES)
FUNCTIONAL_NODE_DAMAGE = "damage"
FUNCTIONAL_NODE_BUFF = "buff"
FUNCTIONAL_NODE_DEBUFF = "debuff"
FUNCTIONAL_NODE_SKILL = "skill"
FUNCTIONAL_NODE_SPELL = "spell"
FUNCTIONAL_NODE_PROCESS = "process"
FUNCTIONAL_NODE_TYPES = [
    FUNCTIONAL_NODE_DAMAGE,
    FUNCTIONAL_NODE_BUFF,
    FUNCTIONAL_NODE_DEBUFF,
    FUNCTIONAL_NODE_SKILL,
    FUNCTIONAL_NODE_SPELL,
    FUNCTIONAL_NODE_PROCESS,
]

# Functional node classes (determines when/how nodes are active)
FUNCTIONAL_NODE_CLASS_INNATE = "innate"
FUNCTIONAL_NODE_CLASS_PRIMARY = "primary"
FUNCTIONAL_NODE_CLASS_AUXILIARY = "auxiliary"
FUNCTIONAL_NODE_CLASSES = [
    FUNCTIONAL_NODE_CLASS_INNATE,
    FUNCTIONAL_NODE_CLASS_PRIMARY,
    FUNCTIONAL_NODE_CLASS_AUXILIARY,
]

# Damage subtypes (for damage functional nodes)
DAMAGE_SUBTYPE_PHYSICAL = "physical"
DAMAGE_SUBTYPE_ELEMENTAL = "elemental"
DAMAGE_SUBTYPES = [DAMAGE_SUBTYPE_PHYSICAL, DAMAGE_SUBTYPE_ELEMENTAL]

# Character types
CHARACTER_TYPE_PC = "PC"
CHARACTER_TYPE_NPC = "NPC"
CHARACTER_TYPES = [CHARACTER_TYPE_PC, CHARACTER_TYPE_NPC]

# Equipment slots
SLOT_HEAD = "head"
SLOT_CHEST = "chest"
SLOT_LEGS = "legs"
SLOT_FEET = "feet"
SLOT_HANDS = "hands"
SLOT_RING = "ring"
SLOT_AMULET = "amulet"
EQUIPMENT_SLOTS = [
    SLOT_HEAD,
    SLOT_CHEST,
    SLOT_LEGS,
    SLOT_FEET,
    SLOT_HANDS,
    SLOT_RING,
    SLOT_AMULET,
]

# Stat ranges
STAT_MIN = 0
STAT_MAX = 100

# Skill level ranges
SKILL_LEVEL_MIN = 0
SKILL_LEVEL_MAX = 100

# Default values
DEFAULT_STAT_VALUE = 50
DEFAULT_SKILL_LEVEL = 0
DEFAULT_EYESIGHT = 50
DEFAULT_NIGHT_VISION = 10
DEFAULT_ELEMENTAL_AFFINITY = 0

# Regen types
REGEN_TYPE_HP = "hp"
REGEN_TYPE_MANA = "mana"
REGEN_TYPE_STAMINA = "stamina"
REGEN_TYPES = [REGEN_TYPE_HP, REGEN_TYPE_MANA, REGEN_TYPE_STAMINA]

